apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: springboot-rest-devops-dev
  namespace: argocd
  labels:
    name: springboot-rest-devops-dev
spec:
  project: default
  source:
    repoURL: https://github.com/hei9gag/app-config.git
    targetRevision: HEAD
    path: app-configs/springboot-rest-devops/dev
    helm:    
      # Helm values files for overriding values in the helm chart
      # The path is relative to the spec.source.path directory defined above
      valueFiles:
      - values.yaml
  destination: 
    server: https://kubernetes.default.svc
    namespace: springboot-rest-devops  
  syncPolicy:
    automated:
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
    syncOptions:
    - CreateNamespace=true # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.
    