apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ include "springboot-rest-devops.fullname" . }}
  labels:
    app:  {{ include "springboot-rest-devops.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "springboot-rest-devops.fullname" . }}
  replicas: {{ .Values.deployment.replicaCount }}
  strategy:
    rollingUpdate:
      maxSurge: 30%
      maxUnavailable: 30%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  {{ include "springboot-rest-devops.fullname" . }}
    spec:      
      containers:
      - name:  {{ include "springboot-rest-devops.fullname" . }}
        image:  '{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}'
        resources:
          requests:
            cpu: {{ .Values.deployment.resources.request.cpu }}
            memory: {{ .Values.deployment.resources.request.memory }}
          limits:
            cpu: {{ .Values.deployment.resources.limit.cpu }}
            memory: {{ .Values.deployment.resources.limit.memory }}
        ports:
        - containerPort: {{ .Values.deployment.port }}
      restartPolicy: Always