# Default values for springboot-rest.
replicaCount: 1
port: 8080

image:
  repository: brianhei/spring-application
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.0.1"

resources:
  request:
    cpu: 200m
    memory: 1000Mi
  limit:
    cpu: 400m
    memory: 2000Mi

ingress:
  host: bc.demo.com
  path: /