apiVersion: apps/v1
kind: Deployment
metadata:
  name:  springboot-rest-devops
  labels:
    app:  springboot-rest-devops
spec:
  selector:
    matchLabels:
      app: springboot-rest-devops
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 30%
      maxUnavailable: 30%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  springboot-rest-devops
    spec:      
      containers:
      - name:  springboot-rest-devops
        image:  "brianhei/spring-application:0.0.1"
        resources:
          requests:
            cpu: 200m
            memory: 1000Mi
          limits:
            cpu: 400m
            memory: 2000Mi
        ports:
        - containerPort:  8080          
      restartPolicy: Always