apiVersion: apps/v1
kind: Deployment
metadata:
  name:  springboot-rest-devops
  labels:
    app:  springboot-rest-devops
spec:
  selector:
    matchLabels:
      app: springboot-rest-devops
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 30%
      maxUnavailable: 30%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  springboot-rest-devops
    spec:      
      containers:
      - name:  springboot-rest-devops
        image:  "brianhei/spring-application:0.0.1"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
        ports:
        - containerPort:  8080
          name:  springboot-rest-devops
      restartPolicy: Always